In [ ]:
## !/usr/bin/python3

# 
# 2020年12月28日


# Python3实现循环链表

def func()->bool:
    a = int(input("第一个参数："))
    b = int(input("第二个参数："))
    c = list(input("第三个参数："))
    li = c
#     li=[1,2,3,4,6]
    sum_li = sum(li)
    for index in range(len(li)):
        x = 0
        for i in range(index,len(li)*2):
            if(i >= len(li)):
                i = i % len(li)
            x += li[i]
            if(x==sum_li/2):
                return True
            if(x>sum_li/2):
                break
    return False
            

func()

[1, 2, 3, 4]

In [9]:
import numpy as np
x = np.arange(24).reshape(2,3,4)

print(x,end='\n')
print()
print(x.sum(axis=0))

print('')
 
print(x.sum(axis=1))

print('')
print(x.sum(axis=2))


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[12 15 18 21]
 [48 51 54 57]]

[[ 6 22 38]
 [54 70 86]]


In [29]:
def reverse(x: int) -> int:
        if(x >= 0):
            ans = list(str(x))
            ans.reverse()
            return int("".join(ans)) if int("".join(ans)) <= pow(2,31)-1 else 0
        else:
            if(-1*x>pow(2,32)):
                    return 0
            ans = list(str(x)[1:])
            ans.reverse()
            return int("".join(ans))*-1 if int("".join(ans)) <=pow(2,31) else 0
reverse(-2147483648)

0

In [34]:
def isPalindrome( x: int) -> bool:
        x_str = str(x)
        x_str_array = list(x_str)
        x_str_array.reverse()
        return True if x_str==''.join(x_str_array) else False
isPalindrome(121)

121 121


True